---

# Default runtime environment
container:
    image: quay.io/libpod/cirrus-ci_retrospective:latest


# Actual testing task for code in this repo.
cirrus-ci/actual_test_task:
    env:
        CIRRUS_CLONE_DEPTH: 0
    script:
        - git fetch --tags
        - $CIRRUS_WORKING_DIR/bin/run_all_tests.sh


# CI-Testing (itself) task that always passes + uploads simple artifact
cirrus-ci/test_passing_task:
    script:
        - echo "$CIRRUS_BUILD_ID/$CIRRUS_TASK_ID/pass" > passing_output.log
        - true
    always: &results
        test_artifacts:
            path: '*.log'

# CI-Testing that must be manually triggered
cirrus-ci/test_manual_task:
    depends_on:
        - cirrus-ci/actual_test
        - cirrus-ci/test_passing
    trigger_type: manual
    script:
        - echo "$CIRRUS_BUILD_ID/$CIRRUS_TASK_ID/manual" > manual_output.log
        - true
    always: &results
        test_artifacts:
            path: '*.log'

# CI-Testing (itself) task that always fails in PRs + uploads simple artifact
# cirrus-ci/test_failing_task:
#     script:
#         - echo "$CIRRUS_BUILD_ID/$CIRRUS_TASK_ID/fail" > failing_output.log
#         - test -z "$CIRRUS_PR"  # only fail when running on pull requests
#     always:
#         <<: *results


cirrus-ci/test_success_task:
    depends_on:
        - cirrus-ci/actual_test
        - cirrus-ci/test_passing
        # - cirrus-ci/test_failing
