---

on: [push, pull_request]

jobs:
    actual_test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  # Testing installer requires a full repo. history
                  fetch-depth: 0
                  path: ./
            - run: git fetch --tags
            - run: $GITHUB_WORKSPACE/bin/run_all_tests.sh
              # env:
              #     TEST_DEBUG: 'true'
    debug:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/upload-artifact@v1.0.0
              with:
                  # There is no way to avoid this being zipped :(
                  name: event.json.zip
                  path: ${{ github.event_path }}
