---

on: [push, pull_request]

jobs:
    actual_test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  # Testing installer requires a full repo. history
                  fetch-depth: 0
                  path: ./
            - run: git fetch --tags --force
            - run: $GITHUB_WORKSPACE/bin/run_all_tests.sh
              # env:
              #     TEST_DEBUG: 'true'
    test_build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  path: ./
            - run: >-
                docker build -t quay.io/libpod/cirrus-ci_retrospective:latest \
                    -f cirrus-ci_retrospective/Dockerfile \
                    --build-arg INSTALL_AUTOMATION_VERSION=0.0.0 \
                    ./
    debug:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/upload-artifact@v1.0.0
              with:
                  # There is no way to avoid this being zipped :(
                  name: event.json.zip
                  path: ${{ github.event_path }}
