---

on: [push, pull_request]

jobs:
    actual_test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  path: ./
            - run: $GITHUB_WORKSPACE/bin/run_all_tests.sh
              # env:
              #     TEST_DEBUG: 'true'
    debug:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/upload-artifact@v1.0.0
              with:
                  name: event.json
                  path: ${{ github.event_path }}
