---

on:
    check_suite:
        types:
            - completed

env:
    ACTIONS_SCRIPTS_URL: 'https://raw.githubusercontent.com/${{ github.repository }}/master/.github/actions'
    ACTIONS_STEP_DEBUG: '${{ secrets.ACTIONS_STEP_DEBUG }}'

jobs:
    debug:
        if: github.event.check_suite.app.name == 'Cirrus CI'
        runs-on: ubuntu-latest
        steps:
            - name: Collect the originating event and result JSON
              run: cp "${{ github.event_path }}" ./

            - name: Log colorized and formatted event JSON
              run: jq --indent 4 --color-output . ./event.json

            - name: Execute latest upstream cirrus-ci_retrospective
              id: cirrus-ci_retrospective
              # Can't use ${{env.CCI_RET_TAG}} in 'uses` because dumb stupid
              uses: docker://quay.io/libpod/cirrus-ci_retrospective:v1.1.3
              env:
                GITHUB_TOKEN: ${{ github.token }}

            - if: always()
              name: Log colorized and formatted cirrus-ci_retrospective JSON
              run: jq --indent 4 --color-output . ./cirrus-ci_retrospective.json
    github:
        if: github.event.check_suite.app.name == 'Cirrus CI'
        runs-on: ubuntu-latest
        steps:
            - run: curl --silent --location --url '${{ env.ACTIONS_SCRIPTS_URL }}/${{ github.job }}.sh' | bash -s
            - if: always()
              uses: actions/upload-artifact@v2
              with:
                name: query_and_reply
                path: artifacts/*.json
    cirrus-ci:
        needs: github
        runs-on: ubuntu-latest
        steps:
            - uses: actions/download-artifact@v2
              with:
                  name: query_and_reply
            - run: curl --silent --location --url '${{ env.ACTIONS_SCRIPTS_URL }}/${{ github.job }}.sh' | bash -s
