---

on:
    check_suite:  # ALWAYS triggered from the default branch
        # Ref: https://help.github.com/en/actions/reference/events-that-trigger-workflows#check-suite-event-check_suite
        types:
            - completed

jobs:
    # Use the latest published version of the cirrus-ci_retrospective action to
    # determine the execution context of _this_ workflow run.
    cirrus-ci_retrospective:
        # Do not execute for other github applications, only works with cirrus-ci
        if: github.event.check_suite.app.name == 'Cirrus CI'
        runs-on: ubuntu-latest
        steps:
            - id: cirrus-ci_retrospective
              uses: docker://quay.io/libpod/cirrus-ci_retrospective:latest
              env:
                GITHUB_TOKEN: ${{ github.token }}

            # Help debug any problems from above
            # N/B: This output can't be used as JSON anywhere in GH Action YAML
            - run: echo '${{ toJSON(steps.cirrus-ci_retrospective.outputs.json) }}'

            - id: success_pr
              shell: bash
              run: >-
                  printf \
                  "::set-output name=value::%s" \
                  $(jq '.[] | select(.name == "cirrus-ci/test_success") | .build.pullRequest' \
                    ./cirrus-ci_retrospective.json)

            # pullRequest is 'null' when Cirrus-CI build was NOT a pull request
            # Github will coerces 'null' to '0'
            - if: steps.success_pr.outputs.value
              # Needed to clone the code from PR HEAD
              id: success_sha
              shell: bash
              run: >-
                  printf \
                  "::set-output name=value::%s" \
                  $(jq '.[] | select(.name == "cirrus-ci/test_success") | .build.changeIdInRepo' \
                    ./cirrus-ci_retrospective.json)

            - if: steps.success_pr.outputs.value
              uses: actions/checkout@v2
              with:
                  ref: ${{ steps.success_sha.value }}
                  path: ./

            # Execute the PR's version of the cirrus-ci_retrospective script in debugging mode
            - if: steps.success_pr.outputs.value
              run: $GITHUB_WORKSPACE/cirrus-ci_retrospective/bin/debug.sh &> $GITHUB_WORKSPACE/debug.output
              env:
                GITHUB_EVENT_PATH: ${{ github.event_path }}
                GITHUB_WORKSPACE: ${{ github.workspace }}
                GITHUB_TOKEN: ${{ github.token }}
                DEBUG: 'true'

            - if: steps.success_pr.outputs.value
              uses: actions/upload-artifact@v1.0.0
              with:
                  name: cirrus-ci_retrospective.json.zip
                  path: ./cirrus-ci_retrospective.json

            # FIXME: Just a stub
            # Provide the output and a link as feedback to the PR author
            - if: steps.success_pr.outputs.value
              shell: bash
              run: cat ./debug.output

    debug:
        # Avoid useless executions
        if: github.event.check_suite.app.name == 'Cirrus CI'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/upload-artifact@v1.0.0
              with:
                  # There is no way to avoid this being zipped :(
                  name: event.json.zip
                  path: ${{ github.event_path }}
