---

on:
    check_suite:  # ALWAYS triggered from the default branch
        # Ref: https://help.github.com/en/actions/reference/events-that-trigger-workflows#check-suite-event-check_suite
        types:
            - completed

jobs:
    # Use the latest published version of the cirrus-ci_retrospective action to
    # determine the execution context of _this_ workflow run.
    cirrus-ci_retrospective:
        # Do not execute for other github applications, only works with cirrus-ci
        if: github.event.check_suite.app.name == 'Cirrus CI'
        runs-on: ubuntu-latest
        steps:
            - id: cirrus-ci_retrospective
              uses: docker://quay.io/libpod/cirrus-ci_retrospective:latest
              env:
                GITHUB_TOKEN: ${{ github.token }}

            - uses: actions/upload-artifact@v1.0.0
              with:
                  name: cirrus-ci_retrospective.json.zip
                  path: ./cirrus-ci_retrospective.json

            - id: retro
              shell: bash
              run: |
                  prn=$(jq '.[] | select(.name == "cirrus-ci/test_success") | .build.pullRequest' ./cirrus-ci_retrospective.json)
                  sha=$(jq '.[] | select(.name == "cirrus-ci/test_success") | .build.changeIdInRepo' ./cirrus-ci_retrospective.json)
                  if [[ -n "$prn" ]] && [[ "$prn" != "null" ]] && [[ $prn -gt 0 ]] && [[ -n "$sha" ]]; then
                      printf "\n::set-output name=was_pr::true\n"
                      printf "\n::set-output name=prn::%d\n" "$prn"
                  else
                      printf "\n::set-output name=was_pr::false\n"
                      printf "\n::set-output name=prn::null\n"
                  fi
                  printf "\n::set-output name=sha::%s\n" "$sha"

            - if: always()
              run: |
                  echo "${{ steps.retro.outputs.was_pr }}"
                  echo "${{ steps.retro.outputs.prn }}"
                  echo "${{ steps.retro.outputs.sha }}"

            - if: steps.retro.outputs.was_pr == 'true'
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
                  path: ./pull_request
                  # ignored for some inexplicable reason
                  # ref: ${{ steps.retro.outputs.sha }}

            - if: steps.retro.outputs.was_pr == 'true'
              run: |
                  mkdir -p test_artifacts
                  cd pull_request
                  git fetch origin "${{ steps.retro.outputs.sha }}"
                  git checkout -b 'pr${{ steps.retro.outputs.prn }}' FETCH_HEAD
                  git log -1 | tee ../test_artifacts/commit.txt

            - if: steps.retro.outputs.was_pr == 'true'
              run: |
                  cd pull_request
                  docker build -t test_container \
                        -f cirrus-ci_retrospective/Dockerfile \
                        --build-arg INSTALL_AUTOMATION_VERSION=0.0.0 \
                        ./ &> ../test_artifacts/build_output.txt
              #   TODO: Not sure if this is helpful to have or not
              #   docker save test_container | gzip > ../test_artifacts/test_container.tar.gz

            - if: steps.retro.outputs.was_pr == 'true'
              env:
                  GITHUB_EVENT_PATH: /github/workflow/event.json
                  GITHUB_WORKSPACE: /github/workspace
                  GITHUB_TOKEN: ${{ github.token }}
              run: |
                  cd pull_request
                  github_event_dirpath=$(dirname "${{ github.event_path }}")
                  /usr/bin/docker run --rm \
                      -e GITHUB_TOKEN -e GITHUB_EVENT_PATH -e GITHUB_ACTIONS=true \
                      -v "$PWD":"/github/workspace" \
                      -v $github_event_dirpath:/github/workflow:ro \
                      --entrypoint=/bin/bash test_container \
                      -c "source /etc/profile && exec /usr/share/automation/bin/debug.sh" \
                      &> ../test_artifacts/debug_output.txt
                  mv ./cirrus-ci_retrospective.json ../test_artifacts/ || true

            - if: always() && steps.retro.outputs.was_pr == 'true'
              uses: actions/upload-artifact@v1.0.0
              with:
                  name: test_artifacts.zip
                  path: ./test_artifacts

            # TODO: Post link for test_artifacts.zip into a comment of PR

    debug:
        # Avoid useless executions
        if: github.event.check_suite.app.name == 'Cirrus CI'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/upload-artifact@v1.0.0
              with:
                  # There is no way to avoid this being zipped :(
                  name: event.json.zip
                  path: ${{ github.event_path }}
