---

on:
    check_suite:  # ALWAYS triggered from the default branch
        # Ref: https://help.github.com/en/actions/reference/events-that-trigger-workflows#check-suite-event-check_suite
        types: [completed]

jobs:
    cirrus-ci_retrospective:
        # Do not execute for other github applications, only works with cirrus-ci
        if: github.event.check_suite.app.name == 'Cirrus CI'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  # Respect event context, always run from default_branch
                  ref: ${{ github.event.repository.default_branch }}
                  persist-credentials: false
                  path: ./
            # TODO: Make this into an action (container image)
            - run: $GITHUB_WORKSPACE/bin/cirrus-ci_retrospective.sh
              env:
                GITHUB_TOKEN: ${{ github.token }}
                # DEBUG: 'true'
            - uses: actions/upload-artifact@v1.0.0
              with:
                  name: cirrus-ci_retrospective
                  # Script (above) generate this filename
                  path: ./cirrus-ci_retrospective.json
    event_debug:
        # Avoid useless executions
        if: github.event.check_suite.app.name == 'Cirrus CI'
        runs-on: ubuntu-latest
        steps:
            - uses: hmarr/debug-action@v1.0.0
