---

# Required to un-FUBAR ${{github.workflow}}
name: cirrus-ci_retrospective

on:
    check_suite:
        types:
            - completed

env:
    # Ref: https://help.github.com/en/actions/configuring-and-managing-workflows/managing-a-workflow-run#enabling-step-debug-logging
    ACTIONS_STEP_DEBUG: '${{ secrets.ACTIONS_STEP_DEBUG }}'

jobs:
    github:
        if: github.event.check_suite.app.name == 'Cirrus CI'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  ref: master  # For clarity - workflow always/only runs from master branch
                  persist-credentials: false
                  path: .
            - shell: bash
              env:
                  GITHUB_TOKEN: ${{ github.token }}
              # Assumes checkout of master into ./<repo name>/
              run: ./$(basename $PWD)/.github/actions/${{ github.workflow }}/${{ github.job }}.sh
            - if: always()
              uses: actions/upload-artifact@v2
              with:
                  name: ${{ github.job }}_artifacts
                  path: artifacts/*.json
    cirrus-ci:
        needs: github
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  persist-credentials: false
                  path: .
            - uses: actions/download-artifact@v2
              with:
                  name: github_artifacts
            - shell: bash
              env:
                  GITHUB_TOKEN: ${{ github.token }}
              run: ./$(basename $PWD)/.github/actions/${{ env.GITHUB_WORKFLOW }}/${{ github.job }}.sh
            - if: always()
              uses: actions/upload-artifact@v2
              with:
                  ref: master
                  name: ${{ github.job }}_artifacts
                  path: artifacts/*.json
