---

# Use the latest published version of the cirrus-ci_retrospective container
# to determine the execution context of _this_ workflow run.  If it is a
# pull request, clone the HEAD used in the PR's Cirrus-CI build.  From the PR
# code, build a test version of the cirrus-ci_retrospective container.  Execute
# the test container against the originating Github Actions event.
# Collect and provide outputs in an archive file for analysis.

on:
    check_suite:  # ALWAYS triggered from the default branch
        # Ref: https://help.github.com/en/actions/reference/events-that-trigger-workflows#check-suite-event-check_suite
        types:
            - completed

# Variables required by multiple jobs/steps
env:
    # Authoritative Cirrus-CI task to monitor for completion info of all other cirrus-ci tasks.
    MONITOR_TASK: 'cirrus-ci/success'
    # Authoritative Github Action task (in cirrus-ci) to trigger / check for completion of _this_ workflow
    ACTION_TASK: 'github-actions/success'
    # These same variables and filters need to be used multiple times under varying conditions
    set_task_vars: |
        prn=$(jq --raw-output '.[] | select(.name == "${MONITOR_TASK}") | .build.pullRequest' ./cirrus-ci_retrospective.json)
        tid=$(jq --raw-output '.[] | select(.name == "${ACTION_TASK}") | .id' ./cirrus-ci_retrospective.json)
        sha=$(jq --raw-output '.[] | select(.name == "${MONITOR_TASK}") | .build.changeIdInRepo' ./cirrus-ci_retrospective.json)
        tst=$(jq --raw-output '.[] | select(.name == "${ACTION_TASK}") | .status' ./cirrus-ci_retrospective.json)
        was_pr='false'
        do_intg='false'
        if [[ -n "$prn" ]] && [[ "$prn" != "null" ]] && [[ $prn -gt 0 ]]; then
            was_pr='true'
            if [[ -n "$tst" ]] && [[ "$tst" == "paused" ]]; then
                do_intg='true'
            fi
        fi
    # Help debug filter/data problems
    debug_task_vars: |
        echo "Shell variables set:"
        ${{ env.set_task_vars }}
        echo "Cirrus-CI ran on pr: $was_pr"
        echo "Monitor PR Number: ${prn}"
        echo "Monitor SHA: ${sha}"
        echo "Action Task ID was: ${tid}"
        echo "Action Task Status: ${tst}"
        echo "Do integration testing: ${do_intg}"
        echo ""
        echo "Analyzed Cirrus-CI monitoring task:"
        jq --indent 4 --color-output '.[] | select(.name == "${MONITOR_TASK}")' ./cirrus-ci_retrospective.json
        echo "Analyzed Cirrus-CI action task:"
        jq --indent 4 --color-output '.[] | select(.name == "${ACTION_TASK}")' ./cirrus-ci_retrospective.json

jobs:
    # Obtain task details and validate required execution conditions
    cirrus-ci_retrospective_smoke:
        # Do not execute for other github applications, only works with cirrus-ci
        if: github.event.check_suite.app.name == 'Cirrus CI'
        runs-on: ubuntu-latest
        steps:
            - name: Execute latest upstream cirrus-ci_retrospective
              # Actually use the (not-normally recommended) latest version,
              # since it likely represents the behaviors most similar to
              # what this action expects.
              uses: docker://quay.io/libpod/cirrus-ci_retrospective:latest
              env:
                GITHUB_TOKEN: ${{ github.token }}

            # Consume the output JSON from running the container (above).
            # This could be made into a complete/sophisticated script.  However,
            # In this workflow, if the build was on PR in this repo, we will be
            # re-execute the PR version of the container anyway, so this can
            # remain simple inline commands.
            - name: Check output for a Cirrus-CI build versus Pull Request
              id: retro
              shell: bash
              run: |
                  ${set_task_vars}
                  printf "\n::set-output name=was_pr::%s\n" "$was_pr"
                  printf "\n::set-output name=prn::%d\n" "$prn"
                  printf "\n::set-output name=tid::%s\n" "$tid"
                  printf "\n::set-output name=sha::%s\n" "$sha"
                  printf "\n::set-output name=tst::%s\n" "$tst"

            # In case there was a problem, provide details about what might have gone wrong.
            - if: always()
              name: Debug latest upstream cirrus-ci_retrospective output Values
              run: |
                  ${debug_task_vars}

            # Negative case, abnormal workflow ($ACTION-TASK task already ran / not paused).
            - if: steps.retro.outputs.was_pr == 'true' && steps.retro.outputs.tst != 'paused'
              id: create_error_pr_comment
              name: Create a status comment in the PR
              # Ref: https://github.com/marketplace/actions/comment-action
              uses: jungwinter/comment@v1
              with:
                  issue_number: '${{ steps.retro.outputs.prn }}'
                  type: 'create'
                  token: '${{ secrets.GITHUB_TOKEN }}'
                  body: >-
                      ***ERROR***: [cirrus-ci_retrospective
                      action](https://github.com/${{github.repository}}/actions/runs/${{github.run_id}})
                      found `${{ env.ACTION_TASK }}` task with unexpected `${{ steps.retro.outputs.tst }}`
                      status. This task should never be triggered manually (or multiple times) under normal
                      circumstances.

            # Negative case followup, fail the build with an error
            - if: steps.retro.outputs.was_pr == 'true' && steps.retro.outputs.tst != 'paused'
              run: >-
                  printf "::error::Found ${ACTION_TASK} with unexpected ${{ steps.retro.outputs.tst }} status"
                  exit 1

    # Execute in parallel with smoke (above) to improve overall performance
    cirrus-ci_retrospective:
        if: github.event.check_suite.app.name == 'Cirrus CI'
        runs-on: ubuntu-latest
        steps:
            - name: Execute latest upstream cirrus-ci_retrospective
              uses: docker://quay.io/libpod/cirrus-ci_retrospective:latest
              env:
                GITHUB_TOKEN: ${{ github.token }}

            - name: Check output for a Cirrus-CI build versus Pull Request
              id: retro
              shell: bash
              run: |
                  ${set_task_vars}
                  printf "\n::set-output name=prn::%d\n" "$prn"
                  printf "\n::set-output name=tid::%s\n" "$tid"
                  printf "\n::set-output name=sha::%s\n" "$sha"
                  printf "\n::set-output name=tst::%s\n" "$tst"
                  printf "\n::set-output name=do_intg::%s\n" "$do_intg"

            # Same failure condition as smoke job
            - if: steps.retro.outputs.do_intg != 'true'
              run: exit 1

            # Provide feedback in PR for normal workflow ($ACTION-TASK task has not run).
            - if: steps.retro.outputs.do_intg == 'true'
              id: create_pr_comment
              name: Create a status comment in the PR
              # Ref: https://github.com/marketplace/actions/comment-action
              uses: jungwinter/comment@v1
              with:
                  issue_number: '${{ steps.retro.outputs.prn }}'
                  type: 'create'
                  token: '${{ secrets.GITHUB_TOKEN }}'
                  # N/B: At the time of this comment, it is not possible to provide
                  # direct links to specific job-steps (here) nor links to artifact
                  # files.  There are open RFE's for this capability to be added.
                  body: >-
                      [Cirrus-CI Retrospective Github
                      Action](https://github.com/${{github.repository}}/actions/runs/${{github.run_id}})
                      has started.  Running against
                      [${{ steps.retro.outputs.sha }}](https://github.com/${{github.repository}}/pull/${{steps.retro.outputs.prn}}/commits/${{steps.retro.outputs.sha}})
                      in this pull request.

            # Since we're executing from the master branch, github will silently
            # block allow direct checkout of PR code.
            - if: steps.retro.outputs.do_intg == 'true'
              name: Clone all repository code
              uses: actions/checkout@v2
              with:
                  # Get ALL available history to avoid problems during any run of
                  # 'git describe' from any script in the repo.
                  fetch-depth: 0
                  path: ./pull_request
                  # Will be used to execute code from the PR
                  # DO NOT build-in any unnecessary permissions
                  persist-credentials: 'false'

            # This workflow always runs from the master branch, this is not helpful
            # for PR authors wanting to change the container or script's behavior.
            # Clone down a copy of the code from the PR, so it may be utilized for
            # a test-build and secondary execution of cirrus-ci_retrospective
            - if: steps.retro.outputs.do_intg == 'true'
              name: Fetch PR code used by Cirrus-CI during completed build
              run: |
                  mkdir -p test_artifacts
                  cp "$GITHUB_EVENT_PATH" test_artifacts/
                  mkdir -p pull_request
                  cd pull_request
                  git fetch origin "${{ steps.retro.outputs.sha }}"
                  git checkout -b 'pr${{ steps.retro.outputs.prn }}' FETCH_HEAD
                  git log -1 | tee ../test_artifacts/commit.txt

            # Update the comment posted to the PR, replace it's content with the current
            # execution status and links.
            - if: steps.retro.outputs.do_intg == 'true'
              id: edit_pr_comment_build
              name: Update status comment on PR
              uses: jungwinter/comment@v1
              with:
                  type: 'edit'
                  comment_id: '${{ steps.create_pr_comment.outputs.id }}'
                  token: '${{ secrets.GITHUB_TOKEN }}'
                  body: >-
                      [Cirrus-CI Retrospective Github
                      Action](https://github.com/${{github.repository}}/actions/runs/${{github.run_id}})
                      is building [test cirrus-ci_retrospective container image
                      Dockerfile](https://github.com/${{ github.repository}}/blob/${{steps.retro.outputs.sha}}/cirrus-ci_retrospective/Dockerfile) from this PR.

            # The Dockerfile and container environment may have changed in addition
            # to scripts.  Re-build a testing container image for use in exercising
            # the code from the PR.
            - if: steps.retro.outputs.do_intg == 'true'
              name: Build cirrus-ci_retrospective container image from PR code
              run: |
                  cd pull_request
                  docker build -t test_container \
                        -f cirrus-ci_retrospective/Dockerfile \
                        --build-arg INSTALL_AUTOMATION_VERSION=0.0.0 \
                        ./ &> ../test_artifacts/build_output.txt

            # The container build can take a few minutes, update status comment when it finishes.
            - if: steps.retro.outputs.do_intg == 'true'
              id: edit_pr_comment_exec
              name: Update status comment on PR again
              uses: jungwinter/comment@v1
              with:
                  type: 'edit'
                  comment_id: '${{ steps.edit_pr_comment_build.outputs.id }}'
                  token: '${{ secrets.GITHUB_TOKEN }}'
                  body: >-
                      [Cirrus-CI Retrospective Github
                      Action](https://github.com/${{github.repository}}/actions/runs/${{github.run_id}})
                      is executing test container.

            # Execute the PR's version of the container, against the same event.json
            # used to trigger this workflow run.
            - if: steps.retro.outputs.do_intg == 'true'
              name: Execute PR's cirrus-ci_retrospective container image
              run: |
                  cd pull_request
                  github_event_dirpath=$(dirname "${{ github.event_path }}")
                  /usr/bin/docker run --rm \
                      -e GITHUB_TOKEN=${{ github.token }} \
                      -e GITHUB_EVENT_PATH=/github/workflow/event.json \
                      -e GITHUB_ACTIONS=true \
                      -e GITHUB_WORKSPACE=/github/workspace \
                      -v "$GITHUB_WORKSPACE/pull_request":"/github/workspace" \
                      -v $github_event_dirpath:/github/workflow \
                      --entrypoint=/bin/bash test_container \
                      -c "source /etc/profile && exec /usr/share/automation/bin/debug.sh" \
                      &> ../test_artifacts/debug_output.txt
                  mv ./cirrus-ci_retrospective.json ../test_artifacts/ || true

            - if: steps.retro.outputs.do_intg == 'true'
              name: Verify output JSON from test container parses for future use by this workflow
              shell: bash
              run: |
                  cd test_artifacts
                  ${set_task_vars}
                  ${debug_task_vars}
                  err() { a=$1; e=$2; echo "::error::Test container \$$a='${!a}', expecting '$e'"; exit 1; }
                  if [[ -z "$prn" ]] || [[ "$prn" != "${{ steps.retro.outputs.prn }}" ]]; then
                      err prn "${{ steps.retro.outputs.prn }}"
                  elif [[ -z "$tid" ]] || [[ "$tid" != "${{ steps.retro.outputs.tid }}" ]]; then
                      err prn "${{ steps.retro.outputs.tid }}"
                  elif [[ -z "$sha" ]] || [[ "$sha" != "${{ steps.retro.outputs.sha }}" ]]; then
                      err prn "${{ steps.retro.outputs.sha }}"
                  elif [[ -z "$tst" ]] || "$tst" != "${{ steps.retro.outputs.tst }}"; then
                      err tst "${{ steps.retro.outputs.tst }}"
                  fi

            # Allow PR to be merged by triggering required action-status marker task in Cirrus CI
            - if: steps.retro.outputs.do_intg == 'true'
              name: Trigger Cirrus-CI ${{ env.ACTION_TASK }} task on PR
              env:
                  # ID invented here to verify the operation performed.
                  UUID: ${{github.run_id}}.${{steps.retro.outputs.prn}}.${{steps.retro.outputs.sha}}
              run: |
                  trap "history -c" EXIT
                  curl --request POST \
                    --url https://api.cirrus-ci.com/graphql \
                    --header '${{ secrets.CIRRUS_CI_AUTH_HEADER }}' \
                    --header 'content-type: application/json' \
                    --data '{"query":"mutation {\n  trigger(input: {taskId: \"${{steps.retro.outputs.tid}}\", clientMutationId: \"${{env.UUID}}\"}) {\n    clientMutationId\n    task {\n      name\n    }\n  }\n}"}' \
                    > ./test_artifacts/action_task_trigger.json

                  actual=$(jq --raw-output '.data.trigger.clientMutationId' ./test_artifacts/manual.json)
                  echo "Verifying returned tracking value"
                  test "$actual" == "$UUID"

            - if: steps.retro.outputs.do_intg == 'true'
              name: Update comment on workflow success
              uses: jungwinter/comment@v1
              with:
                  type: 'edit'
                  comment_id: '${{ steps.edit_pr_comment_exec.outputs.id }}'
                  token: '${{ secrets.GITHUB_TOKEN }}'
                  body: >-
                      Successfully triggered [${{ env.ACTION_TASK }}
                      task](https://cirrus-ci.com/task/${{ steps.retro.outputs.tid }}?command=main#L0)
                      to indicate
                      successful run of [cirrus-ci_retrospective integration
                      testing](https://github.com/${{github.repository}}/actions/runs/${{github.run_id}})
                      from this PR's
                      [${{ steps.retro.outputs.sha }}](https://github.com/${{github.repository}}/pull/${{steps.retro.outputs.prn}}/commits/${{steps.retro.outputs.sha}}).

            - if: failure() && steps.retro.outputs.do_intg == 'true'
              name: Update comment on workflow failure
              uses: jungwinter/comment@v1
              with:
                  type: 'edit'
                  comment_id: '${{ steps.create_pr_comment.outputs.id }}'
                  token: '${{ secrets.GITHUB_TOKEN }}'
                  body: >-
                      Failure running [Cirrus-CI Retrospective Github
                      Action](https://github.com/${{github.repository}}/actions/runs/${{github.run_id}})
                      failed against this PR's
                      [${{ steps.retro.outputs.sha }}](https://github.com/${{github.repository}}/pull/${{steps.retro.outputs.prn}}/commits/${{steps.retro.outputs.sha}})

            # This can happen because of --force push, manual cancel button press, or some other cause.
            - if: cancelled() && steps.retro.outputs.do_intg == 'true'
              name: Update comment on workflow cancellation
              uses: jungwinter/comment@v1
              with:
                  type: 'edit'
                  comment_id: '${{ steps.create_pr_comment.outputs.id }}'
                  token: '${{ secrets.GITHUB_TOKEN }}'
                  body: '[Cancelled](https://github.com/${{github.repository}}/pull/${{steps.retro.outputs.prn}}/commits/${{steps.retro.outputs.sha}})'

            # Provide an archive of files for debugging/analysis.
            - if: always() && steps.retro.outputs.do_intg == 'true'
              name: Archive event, build, and debugging output
              uses: actions/upload-artifact@v1.0.0
              with:
                  name: pr_${{ steps.retro.outputs.prn }}_debug.zip
                  path: ./test_artifacts
