---

on:
    check_suite:
        types:
            - completed

env:
    # Ref: https://help.github.com/en/actions/configuring-and-managing-workflows/managing-a-workflow-run#enabling-step-debug-logging
    ACTIONS_STEP_DEBUG: '${{ secrets.ACTIONS_STEP_DEBUG }}'
    # Workflow does not have access to source repository, store dependent scripts as gists instead.
    GIST_SCRIPTS_URL: 'https://gist.githubusercontent.com/cevich/165f6477745cc2e9ec048f169155fd83/raw'

jobs:
    github:
        if: github.event.check_suite.app.name == 'Cirrus CI'
        runs-on: ubuntu-latest
        steps:
            - shell: bash
              env:
                  GITHUB_TOKEN: ${{ github.token }}
              # Avoid needing to embed scripts into this YAML
              run: |
                  GIST_SH=$(mktemp -p '' ${{ github.job }}_XXXX.sh)
                  curl --silent --location --url '${{ env.GIST_SCRIPTS_URL }}/${{ github.job }}.sh' -o $GIST_SH
                  source $GIST_SH
            - if: always()
              uses: actions/upload-artifact@v2
              with:
                  name: query_and_reply
                  path: artifacts/*.json
    cirrus-ci:
        needs: github
        runs-on: ubuntu-latest
        steps:
            - uses: actions/download-artifact@v2
              with:
                  name: query_and_reply
            - shell: bash
              env:
                  GITHUB_TOKEN: ${{ github.token }}
              run: |
                  GIST_SH=$(mktemp -p '' ${{ github.job }}_XXXX.sh)
                  curl --silent --location --url '${{ env.GIST_SCRIPTS_URL }}/${{ github.job }}.sh' -o $GIST_SH
                  source $GIST_SH
