---

# see publish_release.yml
on:
    # ref: https://help.github.com/en/actions/reference/events-that-trigger-workflows#release-event-release
    release:
        types:
            - published

jobs:
    container_image:
        runs-on: ubuntu-latest
        env:
            REGISTRY: quay.io
            REPO_USER: libpod
            REPO_NAME: cirrus-ci_retrospective
        steps:
            - uses: actions/checkout@v2
              with:
                  path: ./
            - run: >-
                docker build -t $REGISTRY/$REPO_USER/$REPO_NAME:latest
                    -f cirrus-ci_retrospective/Dockerfile \
                    --build-arg INSTALL_AUTOMATION_VERSION=0.0.0 \
                    ./
            - shell: bash
              env:
                  DOCKER_CONFIG_JSON: ${{secrets.DOCKER_CONFIG_JSON}}
              run: |
                  trap "history -c" EXIT
                  mkdir -p $HOME/.docker
                  echo "$DOCKER_CONFIG_JSON" > $HOME/.docker/config.json
            # $GITHUB_REF guaranteed to be the tag name
            - run: |
                  docker tag $REGISTRY/$REPO_USER/$REPO_NAME:latest \
                             $REGISTRY/$REPO_USER/$REPO_NAME:$GITHUB_REF
                  docker push $REGISTRY/$REPO_USER/$REPO_NAME:$GITHUB_REF && \
                  docker push $REGISTRY/$REPO_USER/$REPO_NAME:latest
    debug:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/upload-artifact@v1.0.0
              with:
                  # There is no way to avoid this being zipped :(
                  name: event.json.zip
                  path: ${{ github.event_path }}
