---

# Use the latest published version of the cirrus-ci_retrospective container
# to determine the execution context of _this_ workflow run.  If it is a
# pull request, post the to-be VM/Container image ID string as a comment.

on:
    check_suite:  # ALWAYS triggered from the default branch
        # Ref: https://help.github.com/en/actions/reference/events-that-trigger-workflows#check-suite-event-check_suite
        types:
            - completed

jobs:
    comment_image_id:
        # Do not execute for other github applications, only works with cirrus-ci
        if: github.event.check_suite.app.name == 'Cirrus CI'
        runs-on: ubuntu-latest
        steps:
            - name: Execute latest upstream cirrus-ci_retrospective
              uses: docker://quay.io/libpod/cirrus-ci_retrospective:latest
              env:
                GITHUB_TOKEN: ${{ github.token }}

            - name: Clone latest automation master branch
              uses: actions/checkout@v2
              with:
                  repository: 'containers/automation'
                  fetch-depth: 1
                  path: ./automation
                  # DO NOT build-in any unnecessary permissions
                  persist-credentials: 'false'

            - name: Load cirrus-ci_retrospective JSON into output variables
              id: retro
              run: |
                  source ./automation/github/lib/github_common.sh
                  ccirjson=$GITHUB_WORKSPACE/cirrus-ci_retrospective.json
                  prn=$(jq --raw-output \
                        '.[] | select(.name == "'success'") | .build.pullRequest' \
                        "$ccirjson")
                  bid=$(jq --raw-output \
                        '.[] | select(.name == "'success'") | .build.id' \
                        "$ccirjson")
                  if [[ -n "$prn" ]] && \
                     [[ "$prn" != "null" ]] && \
                     [[ $prn -gt 0 ]]
                  then
                      set_out_var is_pr true
                      set_out_var prn $prn
                      set_out_var bid $bid
                  else
                      set_out_var is_pr false
                  fi

            - name: Add image id comment to pull request
              if: steps.retro.outputs.is_pr == 'true'
              uses: jungwinter/comment@v1
              with:
                  issue_number: '${{ steps.retro.outputs.prn }}'
                  type: 'create'
                  token: '${{ secrets.GITHUB_TOKEN }}'
                  body: >-
                    [Cirrus CI build](https://cirrus-ci.com/build/${{ steps.retro.outputs.bid }})
                    successful. Image ID `c${{ steps.retro.outputs.bid }}` ready for use.

            - name: Debug cirrus-ci_retrospective JSON
              if: ${{ always() }}
              run: jq --indent 4 --color-output . $GITHUB_WORKSPACE/cirrus-ci_retrospective.json
