---

on:
    release:
        types: published

jobs:
    # TODO: Add a section for an actual tagged release
    latest:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  path: ./
            - run: >-
                docker build -t quay.io/libpod/cirrus-ci_retrospective:latest \
                    -f cirrus-ci_retrospective/Dockerfile \
                    --build-arg INSTALL_AUTOMATION_VERSION=0.0.0 \
                    ./
            - shell: bash
              env:
                  DOCKER_CONFIG_JSON: ${{secrets.DOCKER_CONFIG_JSON}}
              run: |
                  trap "history -c" EXIT
                  mkdir -p $HOME/.docker
                  echo "$DOCKER_CONFIG_JSON" > $HOME/.docker/config.json
            - run: docker push quay.io/libpod/cirrus-ci_retrospective:latest
    debug:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/upload-artifact@v1.0.0
              with:
                  # There is no way to avoid this being zipped :(
                  name: event.json.zip
                  path: ${{ github.event_path }}
