---

# Format Ref: https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions

# Required to un-FUBAR default ${{github.workflow}} value
name: test_email

on:
    # Only trigger job manually in github-actions WebUI
    workflow_dispatch: {}

env:
    # Debug-mode can reveal secrets, only enable by a secret value.
    # Ref: https://help.github.com/en/actions/configuring-and-managing-workflows/managing-a-workflow-run#enabling-step-debug-logging
    ACTIONS_STEP_DEBUG: '${{ secrets.ACTIONS_STEP_DEBUG }}'
    # File with CSV listing of zero or more e-mail addresses for delivery
    # of daily failure notice e-mails.
    FAILMAILCSV: './cron-fail_addrs.csv'

jobs:
    test_email:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  ref: master
                  persist-credentials: false

            - id: mailto
              run: printf "::set-output name=csv::%s\n" $(cat "$FAILMAILCSV")

            - if: steps.mailto.outputs.csv != ''
              name: Send failure notification e-mail
              # Ref: https://github.com/dawidd6/action-send-mail
              uses: dawidd6/action-send-mail@v2.2.2
              with:
                server_address: ${{secrets.ACTION_MAIL_SERVER}}
                server_port: 465
                username: ${{secrets.ACTION_MAIL_USERNAME}}
                password: ${{secrets.ACTION_MAIL_PASSWORD}}
                subject: Test message #${{github.run_number}}
                to: ${{steps.mailto.outputs.csv}}
                from: ${{secrets.ACTION_MAIL_SENDER}}
                body: Test message, please ignore.
                attachments: ${{github.event_path}}
